server:
  port: 80

spring:
  # H2 Console ??
  h2:
    console:
      enabled: true
      path: /h2-console

  # H2 Database ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/local;AUTO_SERVER=true
    username: sa
    password: hwajin123!

  #JPA ??
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

# jwt
jwt:
  header: Authorization
  secret: e36fd0343ba9b6d27f75b74d50843bf3d44715a1645f57583a11368acdee1239
  token-validity-in-seconds: 86400